# Generated by Django 6.0.3 on 2026-03-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_imovel', models.CharField(choices=[('AP', 'Apartamento'), ('CS', 'Casa'), ('CO', 'Comercial'), ('TE', 'Terreno')], max_length=2)),
                ('endereco', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('quartos', models.IntegerField(default=0)),
                ('banheiros', models.IntegerField(default=0)),
                ('vagas_garagem', models.IntegerField(default=0)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/')),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='anuncios.anuncio')),
            ],
        ),
    ]
