# Generated by Django 6.0.3 on 2026-03-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='status_imovel',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('VENDIDO', 'Vendido'), ('ALUGADO', 'Alugado')], default='DISPONIVEL', max_length=20),
        ),
    ]
